version: '3.8'

services:
  transliteration-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app